# Generated by Django 5.2 on 2026-09-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order on the site (lower numbers first).')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text="Used in the destination's URL, e.g. /destinations/osaka/. Leave blank to auto-generate from the name.", max_length=120, unique=True)),
                ('region', models.CharField(blank=True, help_text='e.g. Kansai, Kanto, Kyushu — shown as the small label above the destination name.', max_length=100)),
                ('short_description', models.CharField(blank=True, help_text='Short teaser shown on destination cards (home page and destinations grid).', max_length=200)),
                ('description', models.TextField(help_text="Longer description shown on the destination's own detail page.")),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide this destination from the site without deleting it.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Untick to hide this service from the site without deleting it.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls display order on the site (lower numbers first). Also used to generate the displayed 01/02/03 service number.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
